# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true
plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown

# Setup
title:            zpYcho's Blog
tagline:          'Lelouch Lamperouge'
description:      'Yet another blog from a cyber security enthusiast'
url:              https://ziednamouchi.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
